### ISSUE TITLE
module configuration and webpack/sass-loader support

### ISSUE THREAD

**Issue by ricokahler** [PredixDev/px-starter-kit-design#1]
I'm a bit confused on how bundle the different modules together. **Could you explain how to compile all the different predix-ui modules into one css?**

Below is what I've tried:

---

The first thing I do is install the bower dependencies in my main folder like so:

```bash
bower install --save https://github.com/PredixDev/px-starter-kit-design.git
```

And that presents me with this `bower_components` folder structure

```
 Directory of C:\Users\212446691\workspace\mini-maples\bower_components

02/21/2017  11:39 PM    <DIR>          .
02/21/2017  11:39 PM    <DIR>          ..
02/21/2017  11:39 PM                 0 dir.txt
02/21/2017  11:31 PM    <DIR>          inuit-clearfix
02/21/2017  11:31 PM    <DIR>          inuit-functions
02/21/2017  11:31 PM    <DIR>          inuit-responsive-settings
02/21/2017  11:31 PM    <DIR>          inuit-responsive-tools
02/21/2017  11:31 PM    <DIR>          px-box-sizing-design
02/21/2017  11:31 PM    <DIR>          px-colors-design
02/21/2017  11:31 PM    <DIR>          px-defaults-design
02/21/2017  11:31 PM    <DIR>          px-flexbox-design
02/21/2017  11:31 PM    <DIR>          px-functions-design
02/21/2017  11:31 PM    <DIR>          px-helpers-design
02/21/2017  11:31 PM    <DIR>          px-mixins-design
02/21/2017  11:31 PM    <DIR>          px-normalize-design
02/21/2017  11:31 PM    <DIR>          px-spacing-design
02/21/2017  11:31 PM    <DIR>          px-spacing-responsive-design
02/21/2017  11:31 PM    <DIR>          px-starter-kit-design
02/21/2017  11:31 PM    <DIR>          px-typography-design
02/21/2017  11:31 PM    <DIR>          px-viewport-design
02/21/2017  11:31 PM    <DIR>          px-widths-design
02/21/2017  11:31 PM    <DIR>          px-widths-responsive-design
02/21/2017  11:31 PM    <DIR>          px-widths-tools-design
               1 File(s)              0 bytes
              22 Dir(s)  183,641,309,184 bytes free
```

And then in the folder up (out of `bower_components`), I create a `main.scss`:

```
// Settings
@import "bower_components/px-colors-design/_settings.colors.scss";

// Tools

// Generic
@import "bower_components/px-normalize-design/_generic.normalize.scss";
@import "bower_components/px-box-sizing-design/_generic.box-sizing.scss";
@import "bower_components/px-helpers-design/_generic.helpers.scss";

// Base
@import "bower_components/px-flexbox-design/_base.flexbox.scss";
@import "bower_components/px-viewport-design/_base.viewport.scss";
@import "bower_components/px-typography-design/_base.typography.scss";

// Meta

// Objects

// Component
// Your css goes in here

// Trumps
@import "bower_components/inuit-clearfix/_trumps.clearfix.scss";
@import "bower_components/px-spacing-responsive-design/_trumps.spacing-responsive.scss";
@import "bower_components/px-widths-responsive-design/_trumps.widths-responsive.scss";
```

Then finally I try to compile it using:

```bash
node-sass main.scss > main.css
```

And i'm presented with this error:

```
{
  "status": 1,
  "file": "C:/Users/212446691/workspace/mini-maples/bower_components/px-normalize-design/_generic.normalize.scss",
  "line": 3,
  "column": 1,
  "message": "File to import not found or unreadable: px-defaults-design/_settings.defaults.scss.\nParent style sheet: C:/Users/212446691/workspace/mini-maples/bower_components/px-normalize-design/_generic.normalize.scss",
  "formatted": "Error: File to import not found or unreadable: px-defaults-design/_settings.defaults.scss.\n       Parent style sheet: C:/Users/212446691/workspace/mini-maples/bower_components/px-normalize-design/_generic.normalize.scss\n        on line 3 of bower_components/p
x-normalize-design/_generic.normalize.scss\n>> @import \"px-defaults-design/_settings.defaults.scss\";\n   ^\n"
}
```

And further investigation shows me that `px-normalize-design/_generic.normalize.scss` has the line:

```scss
@import "px-defaults-design/_settings.defaults.scss";
```

This causes an error because the `px-defaults-design` module is one level up in the `bower_components` folder. If change the above line to:

```scss
@import "../px-defaults-design/_settings.defaults.scss";
```

then it the compilation will get a little further.

---

**So my question is how can I bundle these file together? Am I missing an argument?** How can I compile all the file without having to copy and paste the folders?

### Does the module structure need to be changed?

---

And last but not least: I'd like to get predix-ui working in webpack 2 with the [sass-loader](https://github.com/webpack-contrib/sass-loader). I've tried including `bower_components` in the [`resolve.modules`](https://webpack.js.org/configuration/resolve/?_sm_au_=iFH6S8q224nt7Vvr#resolve-modules) array and then importing the predix-ui modules with [`@import "~...`](https://github.com/webpack-contrib/sass-loader#imports) but the bundle fails for the seeming the same reason:

```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./src/test.scss
Module build failed: 
undefined
^
      File to import not found or unreadable: px-defaults-design/_settings.defaults.scss.
Parent style sheet: C:/Users/212446691/workspace/mini-maples/bower_components/px-normalize-design/_generic.normalize.scss
      in C:\Users\212446691\workspace\mini-maples\bower_components\px-normalize-design\_generic.normalize.scss (line 3, column 1)
 @ ./src/test.scss 4:14-116
 @ ./src/index.js
```

Any ideas?

**Comment by mdwragg** [comment]
Hi,

We use `node-sass-import-once` to deal with relative path wrinkles in the sass build (it also takes care of de-duping imports of sass partials). We use this via gulp.

See here for example of usage:

https://github.com/PredixDev/px-data-table/blob/master/gulpfile.js#L15

If you want to use node-sass for a quick n dirty test, move your 'app' sass to your local bower_components folder, change your paths of your sass partial imports to not have `bower_components` in it and run it again. things should start resolving and compiling 👍 

|- bower_components/
|--- myApp.scss
|-----px-colors-design
|-----px-typography-design
|-----etc.

Never used web-pack sadly, just sounds like a whole complexity I can live without ;-)
